### PR TITLE
update relay install to work with updated spanner

### PR DESCRIPTION
**Pull request by mpeck**
This updates the relay bundle installer to user the new Spanner.Config bits. It also adds some verification for rules and restructures some of the validation code.

resolves operable/cog#273

### CODE REVIEW

**Comment by christophermaier** [comment]
Why isn't the rule verification code in Spanner?

**Comment by mpeck** [comment]
@christophermaier. You are probably missing a bit of context. Spanner validates that the config is properly formed. When we install we validate that the data is actually correct. In the original config validator we were mixing those things up which made things a bit difficult to follow.

For some more context: https://github.com/operable/spanner/blob/master/lib/spanner/config/validator.ex

**Comment by christophermaier** [comment]
@mpeck Still seems that this is something that is fundamentally Spanner's responsibility. When you create a bundle, it'd be nice to know that the rules you've defined are valid at bundle creation time, rather than when it's time to install.

Also, if the validation logic is locked away in Relay, it's not possible to validate the embedded bundle.

**Comment by mpeck** [comment]
@christophermaier hrm, I don't know. I don't necessarily disagree. I just think there should be a clear distinction between syntax errors and semantic errors. We validate that the rules are syntactically valid in Spanner. The installer already does a lot of semantic checks before installing. It was confusing to have that stuff in two places. Also, we don't run validations when creating bundles. At least not for foreign bundles. Everything get's ran during install. 

Rules kinda fall in a weird middle ground I guess.

**Comment by lhaskins** [comment]
LGTM.

**Comment by kevsmith** [comment]
@mpeck @christophermaier I think what we're feeling here is the growing tension between foreign commands and tooling targeted at them and the embedded bundle. I suggested Spanner need only do syntactical validation of rules but I wasn't thinking of the embedded bundle. Special snowflakes, etc, etc.

For expediency's sake we should move more expansive validation back to Spanner (I think this is already done). Definitely need a better solution soon, tho.

**Pull request merged**
